// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: world/v1/world.proto

package worldv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WorldService_AcquireResearchSession_FullMethodName     = "/world.v1.WorldService/AcquireResearchSession"
	WorldService_GetResearchSession_FullMethodName         = "/world.v1.WorldService/GetResearchSession"
	WorldService_WaitResearchSession_FullMethodName        = "/world.v1.WorldService/WaitResearchSession"
	WorldService_RenewLease_FullMethodName                 = "/world.v1.WorldService/RenewLease"
	WorldService_ReleaseResearchSession_FullMethodName     = "/world.v1.WorldService/ReleaseResearchSession"
	WorldService_CreateTarget_FullMethodName               = "/world.v1.WorldService/CreateTarget"
	WorldService_GetTarget_FullMethodName                  = "/world.v1.WorldService/GetTarget"
	WorldService_StartTargetRun_FullMethodName             = "/world.v1.WorldService/StartTargetRun"
	WorldService_WaitTargetRun_FullMethodName              = "/world.v1.WorldService/WaitTargetRun"
	WorldService_StopTargetRun_FullMethodName              = "/world.v1.WorldService/StopTargetRun"
	WorldService_ResetTarget_FullMethodName                = "/world.v1.WorldService/ResetTarget"
	WorldService_DestroyTarget_FullMethodName              = "/world.v1.WorldService/DestroyTarget"
	WorldService_RequestRecovery_FullMethodName            = "/world.v1.WorldService/RequestRecovery"
	WorldService_QuarantineTarget_FullMethodName           = "/world.v1.WorldService/QuarantineTarget"
	WorldService_OpenExec_FullMethodName                   = "/world.v1.WorldService/OpenExec"
	WorldService_OpenTargetExec_FullMethodName             = "/world.v1.WorldService/OpenTargetExec"
	WorldService_PushTargetFile_FullMethodName             = "/world.v1.WorldService/PushTargetFile"
	WorldService_PullTargetFile_FullMethodName             = "/world.v1.WorldService/PullTargetFile"
	WorldService_OpenTargetADB_FullMethodName              = "/world.v1.WorldService/OpenTargetADB"
	WorldService_GetLiveSnapshot_FullMethodName            = "/world.v1.WorldService/GetLiveSnapshot"
	WorldService_SubscribeObservations_FullMethodName      = "/world.v1.WorldService/SubscribeObservations"
	WorldService_SubscribeMetrics_FullMethodName           = "/world.v1.WorldService/SubscribeMetrics"
	WorldService_StartCapture_FullMethodName               = "/world.v1.WorldService/StartCapture"
	WorldService_RequestCapture_FullMethodName             = "/world.v1.WorldService/RequestCapture"
	WorldService_StopCapture_FullMethodName                = "/world.v1.WorldService/StopCapture"
	WorldService_GetObservationBundle_FullMethodName       = "/world.v1.WorldService/GetObservationBundle"
	WorldService_GetIncident_FullMethodName                = "/world.v1.WorldService/GetIncident"
	WorldService_DeclareExport_FullMethodName              = "/world.v1.WorldService/DeclareExport"
	WorldService_PreviewChangeSet_FullMethodName           = "/world.v1.WorldService/PreviewChangeSet"
	WorldService_CommitExport_FullMethodName               = "/world.v1.WorldService/CommitExport"
	WorldService_TransitionAgentGeneration_FullMethodName  = "/world.v1.WorldService/TransitionAgentGeneration"
	WorldService_TransitionTargetGeneration_FullMethodName = "/world.v1.WorldService/TransitionTargetGeneration"
	WorldService_TransitionTargetRun_FullMethodName        = "/world.v1.WorldService/TransitionTargetRun"
	WorldService_CreateTargetOperation_FullMethodName      = "/world.v1.WorldService/CreateTargetOperation"
	WorldService_TransitionTargetOperation_FullMethodName  = "/world.v1.WorldService/TransitionTargetOperation"
	WorldService_CreateIncident_FullMethodName             = "/world.v1.WorldService/CreateIncident"
	WorldService_TransitionIncident_FullMethodName         = "/world.v1.WorldService/TransitionIncident"
	WorldService_GetExec_FullMethodName                    = "/world.v1.WorldService/GetExec"
	WorldService_CreateExec_FullMethodName                 = "/world.v1.WorldService/CreateExec"
	WorldService_TransitionExec_FullMethodName             = "/world.v1.WorldService/TransitionExec"
	WorldService_FinalizeExec_FullMethodName               = "/world.v1.WorldService/FinalizeExec"
)

// WorldServiceClient is the client API for WorldService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// WorldService is the only public control-plane contract. Paths in this API are
// workspace-relative or target-relative; it intentionally has no host shell,
// host executable path, arbitrary mount, Docker socket, or host ADB surface.
type WorldServiceClient interface {
	AcquireResearchSession(ctx context.Context, in *AcquireResearchSessionRequest, opts ...grpc.CallOption) (*AcquireResearchSessionResponse, error)
	GetResearchSession(ctx context.Context, in *GetResearchSessionRequest, opts ...grpc.CallOption) (*ResearchSessionView, error)
	WaitResearchSession(ctx context.Context, in *WaitResearchSessionRequest, opts ...grpc.CallOption) (*ResearchSessionView, error)
	RenewLease(ctx context.Context, in *RenewLeaseRequest, opts ...grpc.CallOption) (*Lease, error)
	ReleaseResearchSession(ctx context.Context, in *ReleaseResearchSessionRequest, opts ...grpc.CallOption) (*ReleaseOutcome, error)
	CreateTarget(ctx context.Context, in *CreateTargetRequest, opts ...grpc.CallOption) (*Target, error)
	GetTarget(ctx context.Context, in *GetTargetRequest, opts ...grpc.CallOption) (*Target, error)
	StartTargetRun(ctx context.Context, in *StartTargetRunRequest, opts ...grpc.CallOption) (*TargetRun, error)
	WaitTargetRun(ctx context.Context, in *WaitTargetRunRequest, opts ...grpc.CallOption) (*TargetRun, error)
	StopTargetRun(ctx context.Context, in *StopTargetRunRequest, opts ...grpc.CallOption) (*ObservationBundle, error)
	ResetTarget(ctx context.Context, in *ResetTargetRequest, opts ...grpc.CallOption) (*Target, error)
	DestroyTarget(ctx context.Context, in *DestroyTargetRequest, opts ...grpc.CallOption) (*Outcome, error)
	RequestRecovery(ctx context.Context, in *RequestRecoveryRequest, opts ...grpc.CallOption) (*RecoveredResource, error)
	QuarantineTarget(ctx context.Context, in *QuarantineTargetRequest, opts ...grpc.CallOption) (*Target, error)
	OpenExec(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ExecFrame, ExecFrame], error)
	OpenTargetExec(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[TargetExecFrame, TargetExecFrame], error)
	PushTargetFile(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[FileTransferFrame, FileTransferFrame], error)
	PullTargetFile(ctx context.Context, in *PullTargetFileRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FileTransferFrame], error)
	OpenTargetADB(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ADBFrame, ADBFrame], error)
	GetLiveSnapshot(ctx context.Context, in *GetLiveSnapshotRequest, opts ...grpc.CallOption) (*LiveSnapshot, error)
	SubscribeObservations(ctx context.Context, in *SubscribeObservationsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ObservationRecord], error)
	SubscribeMetrics(ctx context.Context, in *SubscribeMetricsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MetricSample], error)
	StartCapture(ctx context.Context, in *StartCaptureRequest, opts ...grpc.CallOption) (*Capture, error)
	RequestCapture(ctx context.Context, in *RequestCaptureRequest, opts ...grpc.CallOption) (*Capture, error)
	StopCapture(ctx context.Context, in *StopCaptureRequest, opts ...grpc.CallOption) (*Capture, error)
	GetObservationBundle(ctx context.Context, in *GetObservationBundleRequest, opts ...grpc.CallOption) (*ObservationBundle, error)
	GetIncident(ctx context.Context, in *GetIncidentRequest, opts ...grpc.CallOption) (*Incident, error)
	DeclareExport(ctx context.Context, in *DeclareExportRequest, opts ...grpc.CallOption) (*Export, error)
	PreviewChangeSet(ctx context.Context, in *PreviewChangeSetRequest, opts ...grpc.CallOption) (*ChangeSet, error)
	CommitExport(ctx context.Context, in *CommitExportRequest, opts ...grpc.CallOption) (*Export, error)
	// Driver-facing revision transitions use the same authenticated, revisioned
	// contract and expose every operation currently implemented by Core.
	TransitionAgentGeneration(ctx context.Context, in *TransitionAgentGenerationRequest, opts ...grpc.CallOption) (*AgentWorkspace, error)
	TransitionTargetGeneration(ctx context.Context, in *TransitionTargetGenerationRequest, opts ...grpc.CallOption) (*Target, error)
	TransitionTargetRun(ctx context.Context, in *TransitionTargetRunRequest, opts ...grpc.CallOption) (*TargetRun, error)
	CreateTargetOperation(ctx context.Context, in *CreateTargetOperationRequest, opts ...grpc.CallOption) (*TargetOperation, error)
	TransitionTargetOperation(ctx context.Context, in *TransitionTargetOperationRequest, opts ...grpc.CallOption) (*TargetOperation, error)
	CreateIncident(ctx context.Context, in *CreateIncidentRequest, opts ...grpc.CallOption) (*Incident, error)
	TransitionIncident(ctx context.Context, in *TransitionIncidentRequest, opts ...grpc.CallOption) (*Incident, error)
	GetExec(ctx context.Context, in *GetExecRequest, opts ...grpc.CallOption) (*Exec, error)
	CreateExec(ctx context.Context, in *CreateExecRequest, opts ...grpc.CallOption) (*Exec, error)
	TransitionExec(ctx context.Context, in *TransitionExecRequest, opts ...grpc.CallOption) (*Exec, error)
	FinalizeExec(ctx context.Context, in *FinalizeExecRequest, opts ...grpc.CallOption) (*Exec, error)
}

type worldServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWorldServiceClient(cc grpc.ClientConnInterface) WorldServiceClient {
	return &worldServiceClient{cc}
}

func (c *worldServiceClient) AcquireResearchSession(ctx context.Context, in *AcquireResearchSessionRequest, opts ...grpc.CallOption) (*AcquireResearchSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AcquireResearchSessionResponse)
	err := c.cc.Invoke(ctx, WorldService_AcquireResearchSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *worldServiceClient) GetResearchSession(ctx context.Context, in *GetResearchSessionRequest, opts ...grpc.CallOption) (*ResearchSessionView, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResearchSessionView)
	err := c.cc.Invoke(ctx, WorldService_GetResearchSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *worldServiceClient) WaitResearchSession(ctx context.Context, in *WaitResearchSessionRequest, opts ...grpc.CallOption) (*ResearchSessionView, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResearchSessionView)
	err := c.cc.Invoke(ctx, WorldService_WaitResearchSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *worldServiceClient) RenewLease(ctx context.Context, in *RenewLeaseRequest, opts ...grpc.CallOption) (*Lease, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Lease)
	err := c.cc.Invoke(ctx, WorldService_RenewLease_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *worldServiceClient) ReleaseResearchSession(ctx context.Context, in *ReleaseResearchSessionRequest, opts ...grpc.CallOption) (*ReleaseOutcome, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReleaseOutcome)
	err := c.cc.Invoke(ctx, WorldService_ReleaseResearchSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *worldServiceClient) CreateTarget(ctx context.Context, in *CreateTargetRequest, opts ...grpc.CallOption) (*Target, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Target)
	err := c.cc.Invoke(ctx, WorldService_CreateTarget_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *worldServiceClient) GetTarget(ctx context.Context, in *GetTargetRequest, opts ...grpc.CallOption) (*Target, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Target)
	err := c.cc.Invoke(ctx, WorldService_GetTarget_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *worldServiceClient) StartTargetRun(ctx context.Context, in *StartTargetRunRequest, opts ...grpc.CallOption) (*TargetRun, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TargetRun)
	err := c.cc.Invoke(ctx, WorldService_StartTargetRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *worldServiceClient) WaitTargetRun(ctx context.Context, in *WaitTargetRunRequest, opts ...grpc.CallOption) (*TargetRun, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TargetRun)
	err := c.cc.Invoke(ctx, WorldService_WaitTargetRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *worldServiceClient) StopTargetRun(ctx context.Context, in *StopTargetRunRequest, opts ...grpc.CallOption) (*ObservationBundle, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ObservationBundle)
	err := c.cc.Invoke(ctx, WorldService_StopTargetRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *worldServiceClient) ResetTarget(ctx context.Context, in *ResetTargetRequest, opts ...grpc.CallOption) (*Target, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Target)
	err := c.cc.Invoke(ctx, WorldService_ResetTarget_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *worldServiceClient) DestroyTarget(ctx context.Context, in *DestroyTargetRequest, opts ...grpc.CallOption) (*Outcome, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Outcome)
	err := c.cc.Invoke(ctx, WorldService_DestroyTarget_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *worldServiceClient) RequestRecovery(ctx context.Context, in *RequestRecoveryRequest, opts ...grpc.CallOption) (*RecoveredResource, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecoveredResource)
	err := c.cc.Invoke(ctx, WorldService_RequestRecovery_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *worldServiceClient) QuarantineTarget(ctx context.Context, in *QuarantineTargetRequest, opts ...grpc.CallOption) (*Target, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Target)
	err := c.cc.Invoke(ctx, WorldService_QuarantineTarget_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *worldServiceClient) OpenExec(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ExecFrame, ExecFrame], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &WorldService_ServiceDesc.Streams[0], WorldService_OpenExec_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ExecFrame, ExecFrame]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorldService_OpenExecClient = grpc.BidiStreamingClient[ExecFrame, ExecFrame]

func (c *worldServiceClient) OpenTargetExec(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[TargetExecFrame, TargetExecFrame], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &WorldService_ServiceDesc.Streams[1], WorldService_OpenTargetExec_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TargetExecFrame, TargetExecFrame]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorldService_OpenTargetExecClient = grpc.BidiStreamingClient[TargetExecFrame, TargetExecFrame]

func (c *worldServiceClient) PushTargetFile(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[FileTransferFrame, FileTransferFrame], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &WorldService_ServiceDesc.Streams[2], WorldService_PushTargetFile_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[FileTransferFrame, FileTransferFrame]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorldService_PushTargetFileClient = grpc.BidiStreamingClient[FileTransferFrame, FileTransferFrame]

func (c *worldServiceClient) PullTargetFile(ctx context.Context, in *PullTargetFileRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FileTransferFrame], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &WorldService_ServiceDesc.Streams[3], WorldService_PullTargetFile_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PullTargetFileRequest, FileTransferFrame]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorldService_PullTargetFileClient = grpc.ServerStreamingClient[FileTransferFrame]

func (c *worldServiceClient) OpenTargetADB(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ADBFrame, ADBFrame], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &WorldService_ServiceDesc.Streams[4], WorldService_OpenTargetADB_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ADBFrame, ADBFrame]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorldService_OpenTargetADBClient = grpc.BidiStreamingClient[ADBFrame, ADBFrame]

func (c *worldServiceClient) GetLiveSnapshot(ctx context.Context, in *GetLiveSnapshotRequest, opts ...grpc.CallOption) (*LiveSnapshot, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LiveSnapshot)
	err := c.cc.Invoke(ctx, WorldService_GetLiveSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *worldServiceClient) SubscribeObservations(ctx context.Context, in *SubscribeObservationsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ObservationRecord], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &WorldService_ServiceDesc.Streams[5], WorldService_SubscribeObservations_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeObservationsRequest, ObservationRecord]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorldService_SubscribeObservationsClient = grpc.ServerStreamingClient[ObservationRecord]

func (c *worldServiceClient) SubscribeMetrics(ctx context.Context, in *SubscribeMetricsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MetricSample], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &WorldService_ServiceDesc.Streams[6], WorldService_SubscribeMetrics_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeMetricsRequest, MetricSample]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorldService_SubscribeMetricsClient = grpc.ServerStreamingClient[MetricSample]

func (c *worldServiceClient) StartCapture(ctx context.Context, in *StartCaptureRequest, opts ...grpc.CallOption) (*Capture, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Capture)
	err := c.cc.Invoke(ctx, WorldService_StartCapture_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *worldServiceClient) RequestCapture(ctx context.Context, in *RequestCaptureRequest, opts ...grpc.CallOption) (*Capture, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Capture)
	err := c.cc.Invoke(ctx, WorldService_RequestCapture_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *worldServiceClient) StopCapture(ctx context.Context, in *StopCaptureRequest, opts ...grpc.CallOption) (*Capture, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Capture)
	err := c.cc.Invoke(ctx, WorldService_StopCapture_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *worldServiceClient) GetObservationBundle(ctx context.Context, in *GetObservationBundleRequest, opts ...grpc.CallOption) (*ObservationBundle, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ObservationBundle)
	err := c.cc.Invoke(ctx, WorldService_GetObservationBundle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *worldServiceClient) GetIncident(ctx context.Context, in *GetIncidentRequest, opts ...grpc.CallOption) (*Incident, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Incident)
	err := c.cc.Invoke(ctx, WorldService_GetIncident_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *worldServiceClient) DeclareExport(ctx context.Context, in *DeclareExportRequest, opts ...grpc.CallOption) (*Export, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Export)
	err := c.cc.Invoke(ctx, WorldService_DeclareExport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *worldServiceClient) PreviewChangeSet(ctx context.Context, in *PreviewChangeSetRequest, opts ...grpc.CallOption) (*ChangeSet, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChangeSet)
	err := c.cc.Invoke(ctx, WorldService_PreviewChangeSet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *worldServiceClient) CommitExport(ctx context.Context, in *CommitExportRequest, opts ...grpc.CallOption) (*Export, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Export)
	err := c.cc.Invoke(ctx, WorldService_CommitExport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *worldServiceClient) TransitionAgentGeneration(ctx context.Context, in *TransitionAgentGenerationRequest, opts ...grpc.CallOption) (*AgentWorkspace, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AgentWorkspace)
	err := c.cc.Invoke(ctx, WorldService_TransitionAgentGeneration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *worldServiceClient) TransitionTargetGeneration(ctx context.Context, in *TransitionTargetGenerationRequest, opts ...grpc.CallOption) (*Target, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Target)
	err := c.cc.Invoke(ctx, WorldService_TransitionTargetGeneration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *worldServiceClient) TransitionTargetRun(ctx context.Context, in *TransitionTargetRunRequest, opts ...grpc.CallOption) (*TargetRun, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TargetRun)
	err := c.cc.Invoke(ctx, WorldService_TransitionTargetRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *worldServiceClient) CreateTargetOperation(ctx context.Context, in *CreateTargetOperationRequest, opts ...grpc.CallOption) (*TargetOperation, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TargetOperation)
	err := c.cc.Invoke(ctx, WorldService_CreateTargetOperation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *worldServiceClient) TransitionTargetOperation(ctx context.Context, in *TransitionTargetOperationRequest, opts ...grpc.CallOption) (*TargetOperation, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TargetOperation)
	err := c.cc.Invoke(ctx, WorldService_TransitionTargetOperation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *worldServiceClient) CreateIncident(ctx context.Context, in *CreateIncidentRequest, opts ...grpc.CallOption) (*Incident, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Incident)
	err := c.cc.Invoke(ctx, WorldService_CreateIncident_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *worldServiceClient) TransitionIncident(ctx context.Context, in *TransitionIncidentRequest, opts ...grpc.CallOption) (*Incident, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Incident)
	err := c.cc.Invoke(ctx, WorldService_TransitionIncident_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *worldServiceClient) GetExec(ctx context.Context, in *GetExecRequest, opts ...grpc.CallOption) (*Exec, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Exec)
	err := c.cc.Invoke(ctx, WorldService_GetExec_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *worldServiceClient) CreateExec(ctx context.Context, in *CreateExecRequest, opts ...grpc.CallOption) (*Exec, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Exec)
	err := c.cc.Invoke(ctx, WorldService_CreateExec_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *worldServiceClient) TransitionExec(ctx context.Context, in *TransitionExecRequest, opts ...grpc.CallOption) (*Exec, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Exec)
	err := c.cc.Invoke(ctx, WorldService_TransitionExec_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *worldServiceClient) FinalizeExec(ctx context.Context, in *FinalizeExecRequest, opts ...grpc.CallOption) (*Exec, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Exec)
	err := c.cc.Invoke(ctx, WorldService_FinalizeExec_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorldServiceServer is the server API for WorldService service.
// All implementations must embed UnimplementedWorldServiceServer
// for forward compatibility.
//
// WorldService is the only public control-plane contract. Paths in this API are
// workspace-relative or target-relative; it intentionally has no host shell,
// host executable path, arbitrary mount, Docker socket, or host ADB surface.
type WorldServiceServer interface {
	AcquireResearchSession(context.Context, *AcquireResearchSessionRequest) (*AcquireResearchSessionResponse, error)
	GetResearchSession(context.Context, *GetResearchSessionRequest) (*ResearchSessionView, error)
	WaitResearchSession(context.Context, *WaitResearchSessionRequest) (*ResearchSessionView, error)
	RenewLease(context.Context, *RenewLeaseRequest) (*Lease, error)
	ReleaseResearchSession(context.Context, *ReleaseResearchSessionRequest) (*ReleaseOutcome, error)
	CreateTarget(context.Context, *CreateTargetRequest) (*Target, error)
	GetTarget(context.Context, *GetTargetRequest) (*Target, error)
	StartTargetRun(context.Context, *StartTargetRunRequest) (*TargetRun, error)
	WaitTargetRun(context.Context, *WaitTargetRunRequest) (*TargetRun, error)
	StopTargetRun(context.Context, *StopTargetRunRequest) (*ObservationBundle, error)
	ResetTarget(context.Context, *ResetTargetRequest) (*Target, error)
	DestroyTarget(context.Context, *DestroyTargetRequest) (*Outcome, error)
	RequestRecovery(context.Context, *RequestRecoveryRequest) (*RecoveredResource, error)
	QuarantineTarget(context.Context, *QuarantineTargetRequest) (*Target, error)
	OpenExec(grpc.BidiStreamingServer[ExecFrame, ExecFrame]) error
	OpenTargetExec(grpc.BidiStreamingServer[TargetExecFrame, TargetExecFrame]) error
	PushTargetFile(grpc.BidiStreamingServer[FileTransferFrame, FileTransferFrame]) error
	PullTargetFile(*PullTargetFileRequest, grpc.ServerStreamingServer[FileTransferFrame]) error
	OpenTargetADB(grpc.BidiStreamingServer[ADBFrame, ADBFrame]) error
	GetLiveSnapshot(context.Context, *GetLiveSnapshotRequest) (*LiveSnapshot, error)
	SubscribeObservations(*SubscribeObservationsRequest, grpc.ServerStreamingServer[ObservationRecord]) error
	SubscribeMetrics(*SubscribeMetricsRequest, grpc.ServerStreamingServer[MetricSample]) error
	StartCapture(context.Context, *StartCaptureRequest) (*Capture, error)
	RequestCapture(context.Context, *RequestCaptureRequest) (*Capture, error)
	StopCapture(context.Context, *StopCaptureRequest) (*Capture, error)
	GetObservationBundle(context.Context, *GetObservationBundleRequest) (*ObservationBundle, error)
	GetIncident(context.Context, *GetIncidentRequest) (*Incident, error)
	DeclareExport(context.Context, *DeclareExportRequest) (*Export, error)
	PreviewChangeSet(context.Context, *PreviewChangeSetRequest) (*ChangeSet, error)
	CommitExport(context.Context, *CommitExportRequest) (*Export, error)
	// Driver-facing revision transitions use the same authenticated, revisioned
	// contract and expose every operation currently implemented by Core.
	TransitionAgentGeneration(context.Context, *TransitionAgentGenerationRequest) (*AgentWorkspace, error)
	TransitionTargetGeneration(context.Context, *TransitionTargetGenerationRequest) (*Target, error)
	TransitionTargetRun(context.Context, *TransitionTargetRunRequest) (*TargetRun, error)
	CreateTargetOperation(context.Context, *CreateTargetOperationRequest) (*TargetOperation, error)
	TransitionTargetOperation(context.Context, *TransitionTargetOperationRequest) (*TargetOperation, error)
	CreateIncident(context.Context, *CreateIncidentRequest) (*Incident, error)
	TransitionIncident(context.Context, *TransitionIncidentRequest) (*Incident, error)
	GetExec(context.Context, *GetExecRequest) (*Exec, error)
	CreateExec(context.Context, *CreateExecRequest) (*Exec, error)
	TransitionExec(context.Context, *TransitionExecRequest) (*Exec, error)
	FinalizeExec(context.Context, *FinalizeExecRequest) (*Exec, error)
	mustEmbedUnimplementedWorldServiceServer()
}

// UnimplementedWorldServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWorldServiceServer struct{}

func (UnimplementedWorldServiceServer) AcquireResearchSession(context.Context, *AcquireResearchSessionRequest) (*AcquireResearchSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AcquireResearchSession not implemented")
}
func (UnimplementedWorldServiceServer) GetResearchSession(context.Context, *GetResearchSessionRequest) (*ResearchSessionView, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetResearchSession not implemented")
}
func (UnimplementedWorldServiceServer) WaitResearchSession(context.Context, *WaitResearchSessionRequest) (*ResearchSessionView, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WaitResearchSession not implemented")
}
func (UnimplementedWorldServiceServer) RenewLease(context.Context, *RenewLeaseRequest) (*Lease, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RenewLease not implemented")
}
func (UnimplementedWorldServiceServer) ReleaseResearchSession(context.Context, *ReleaseResearchSessionRequest) (*ReleaseOutcome, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReleaseResearchSession not implemented")
}
func (UnimplementedWorldServiceServer) CreateTarget(context.Context, *CreateTargetRequest) (*Target, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTarget not implemented")
}
func (UnimplementedWorldServiceServer) GetTarget(context.Context, *GetTargetRequest) (*Target, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTarget not implemented")
}
func (UnimplementedWorldServiceServer) StartTargetRun(context.Context, *StartTargetRunRequest) (*TargetRun, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartTargetRun not implemented")
}
func (UnimplementedWorldServiceServer) WaitTargetRun(context.Context, *WaitTargetRunRequest) (*TargetRun, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WaitTargetRun not implemented")
}
func (UnimplementedWorldServiceServer) StopTargetRun(context.Context, *StopTargetRunRequest) (*ObservationBundle, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopTargetRun not implemented")
}
func (UnimplementedWorldServiceServer) ResetTarget(context.Context, *ResetTargetRequest) (*Target, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResetTarget not implemented")
}
func (UnimplementedWorldServiceServer) DestroyTarget(context.Context, *DestroyTargetRequest) (*Outcome, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DestroyTarget not implemented")
}
func (UnimplementedWorldServiceServer) RequestRecovery(context.Context, *RequestRecoveryRequest) (*RecoveredResource, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestRecovery not implemented")
}
func (UnimplementedWorldServiceServer) QuarantineTarget(context.Context, *QuarantineTargetRequest) (*Target, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QuarantineTarget not implemented")
}
func (UnimplementedWorldServiceServer) OpenExec(grpc.BidiStreamingServer[ExecFrame, ExecFrame]) error {
	return status.Errorf(codes.Unimplemented, "method OpenExec not implemented")
}
func (UnimplementedWorldServiceServer) OpenTargetExec(grpc.BidiStreamingServer[TargetExecFrame, TargetExecFrame]) error {
	return status.Errorf(codes.Unimplemented, "method OpenTargetExec not implemented")
}
func (UnimplementedWorldServiceServer) PushTargetFile(grpc.BidiStreamingServer[FileTransferFrame, FileTransferFrame]) error {
	return status.Errorf(codes.Unimplemented, "method PushTargetFile not implemented")
}
func (UnimplementedWorldServiceServer) PullTargetFile(*PullTargetFileRequest, grpc.ServerStreamingServer[FileTransferFrame]) error {
	return status.Errorf(codes.Unimplemented, "method PullTargetFile not implemented")
}
func (UnimplementedWorldServiceServer) OpenTargetADB(grpc.BidiStreamingServer[ADBFrame, ADBFrame]) error {
	return status.Errorf(codes.Unimplemented, "method OpenTargetADB not implemented")
}
func (UnimplementedWorldServiceServer) GetLiveSnapshot(context.Context, *GetLiveSnapshotRequest) (*LiveSnapshot, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLiveSnapshot not implemented")
}
func (UnimplementedWorldServiceServer) SubscribeObservations(*SubscribeObservationsRequest, grpc.ServerStreamingServer[ObservationRecord]) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeObservations not implemented")
}
func (UnimplementedWorldServiceServer) SubscribeMetrics(*SubscribeMetricsRequest, grpc.ServerStreamingServer[MetricSample]) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeMetrics not implemented")
}
func (UnimplementedWorldServiceServer) StartCapture(context.Context, *StartCaptureRequest) (*Capture, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartCapture not implemented")
}
func (UnimplementedWorldServiceServer) RequestCapture(context.Context, *RequestCaptureRequest) (*Capture, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestCapture not implemented")
}
func (UnimplementedWorldServiceServer) StopCapture(context.Context, *StopCaptureRequest) (*Capture, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopCapture not implemented")
}
func (UnimplementedWorldServiceServer) GetObservationBundle(context.Context, *GetObservationBundleRequest) (*ObservationBundle, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetObservationBundle not implemented")
}
func (UnimplementedWorldServiceServer) GetIncident(context.Context, *GetIncidentRequest) (*Incident, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetIncident not implemented")
}
func (UnimplementedWorldServiceServer) DeclareExport(context.Context, *DeclareExportRequest) (*Export, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeclareExport not implemented")
}
func (UnimplementedWorldServiceServer) PreviewChangeSet(context.Context, *PreviewChangeSetRequest) (*ChangeSet, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PreviewChangeSet not implemented")
}
func (UnimplementedWorldServiceServer) CommitExport(context.Context, *CommitExportRequest) (*Export, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CommitExport not implemented")
}
func (UnimplementedWorldServiceServer) TransitionAgentGeneration(context.Context, *TransitionAgentGenerationRequest) (*AgentWorkspace, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TransitionAgentGeneration not implemented")
}
func (UnimplementedWorldServiceServer) TransitionTargetGeneration(context.Context, *TransitionTargetGenerationRequest) (*Target, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TransitionTargetGeneration not implemented")
}
func (UnimplementedWorldServiceServer) TransitionTargetRun(context.Context, *TransitionTargetRunRequest) (*TargetRun, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TransitionTargetRun not implemented")
}
func (UnimplementedWorldServiceServer) CreateTargetOperation(context.Context, *CreateTargetOperationRequest) (*TargetOperation, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTargetOperation not implemented")
}
func (UnimplementedWorldServiceServer) TransitionTargetOperation(context.Context, *TransitionTargetOperationRequest) (*TargetOperation, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TransitionTargetOperation not implemented")
}
func (UnimplementedWorldServiceServer) CreateIncident(context.Context, *CreateIncidentRequest) (*Incident, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateIncident not implemented")
}
func (UnimplementedWorldServiceServer) TransitionIncident(context.Context, *TransitionIncidentRequest) (*Incident, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TransitionIncident not implemented")
}
func (UnimplementedWorldServiceServer) GetExec(context.Context, *GetExecRequest) (*Exec, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetExec not implemented")
}
func (UnimplementedWorldServiceServer) CreateExec(context.Context, *CreateExecRequest) (*Exec, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateExec not implemented")
}
func (UnimplementedWorldServiceServer) TransitionExec(context.Context, *TransitionExecRequest) (*Exec, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TransitionExec not implemented")
}
func (UnimplementedWorldServiceServer) FinalizeExec(context.Context, *FinalizeExecRequest) (*Exec, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FinalizeExec not implemented")
}
func (UnimplementedWorldServiceServer) mustEmbedUnimplementedWorldServiceServer() {}
func (UnimplementedWorldServiceServer) testEmbeddedByValue()                      {}

// UnsafeWorldServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorldServiceServer will
// result in compilation errors.
type UnsafeWorldServiceServer interface {
	mustEmbedUnimplementedWorldServiceServer()
}

func RegisterWorldServiceServer(s grpc.ServiceRegistrar, srv WorldServiceServer) {
	// If the following call pancis, it indicates UnimplementedWorldServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WorldService_ServiceDesc, srv)
}

func _WorldService_AcquireResearchSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcquireResearchSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorldServiceServer).AcquireResearchSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorldService_AcquireResearchSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorldServiceServer).AcquireResearchSession(ctx, req.(*AcquireResearchSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorldService_GetResearchSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetResearchSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorldServiceServer).GetResearchSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorldService_GetResearchSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorldServiceServer).GetResearchSession(ctx, req.(*GetResearchSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorldService_WaitResearchSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WaitResearchSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorldServiceServer).WaitResearchSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorldService_WaitResearchSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorldServiceServer).WaitResearchSession(ctx, req.(*WaitResearchSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorldService_RenewLease_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenewLeaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorldServiceServer).RenewLease(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorldService_RenewLease_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorldServiceServer).RenewLease(ctx, req.(*RenewLeaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorldService_ReleaseResearchSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleaseResearchSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorldServiceServer).ReleaseResearchSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorldService_ReleaseResearchSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorldServiceServer).ReleaseResearchSession(ctx, req.(*ReleaseResearchSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorldService_CreateTarget_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTargetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorldServiceServer).CreateTarget(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorldService_CreateTarget_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorldServiceServer).CreateTarget(ctx, req.(*CreateTargetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorldService_GetTarget_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTargetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorldServiceServer).GetTarget(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorldService_GetTarget_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorldServiceServer).GetTarget(ctx, req.(*GetTargetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorldService_StartTargetRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartTargetRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorldServiceServer).StartTargetRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorldService_StartTargetRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorldServiceServer).StartTargetRun(ctx, req.(*StartTargetRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorldService_WaitTargetRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WaitTargetRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorldServiceServer).WaitTargetRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorldService_WaitTargetRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorldServiceServer).WaitTargetRun(ctx, req.(*WaitTargetRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorldService_StopTargetRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopTargetRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorldServiceServer).StopTargetRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorldService_StopTargetRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorldServiceServer).StopTargetRun(ctx, req.(*StopTargetRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorldService_ResetTarget_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetTargetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorldServiceServer).ResetTarget(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorldService_ResetTarget_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorldServiceServer).ResetTarget(ctx, req.(*ResetTargetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorldService_DestroyTarget_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DestroyTargetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorldServiceServer).DestroyTarget(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorldService_DestroyTarget_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorldServiceServer).DestroyTarget(ctx, req.(*DestroyTargetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorldService_RequestRecovery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestRecoveryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorldServiceServer).RequestRecovery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorldService_RequestRecovery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorldServiceServer).RequestRecovery(ctx, req.(*RequestRecoveryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorldService_QuarantineTarget_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuarantineTargetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorldServiceServer).QuarantineTarget(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorldService_QuarantineTarget_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorldServiceServer).QuarantineTarget(ctx, req.(*QuarantineTargetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorldService_OpenExec_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(WorldServiceServer).OpenExec(&grpc.GenericServerStream[ExecFrame, ExecFrame]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorldService_OpenExecServer = grpc.BidiStreamingServer[ExecFrame, ExecFrame]

func _WorldService_OpenTargetExec_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(WorldServiceServer).OpenTargetExec(&grpc.GenericServerStream[TargetExecFrame, TargetExecFrame]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorldService_OpenTargetExecServer = grpc.BidiStreamingServer[TargetExecFrame, TargetExecFrame]

func _WorldService_PushTargetFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(WorldServiceServer).PushTargetFile(&grpc.GenericServerStream[FileTransferFrame, FileTransferFrame]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorldService_PushTargetFileServer = grpc.BidiStreamingServer[FileTransferFrame, FileTransferFrame]

func _WorldService_PullTargetFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PullTargetFileRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WorldServiceServer).PullTargetFile(m, &grpc.GenericServerStream[PullTargetFileRequest, FileTransferFrame]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorldService_PullTargetFileServer = grpc.ServerStreamingServer[FileTransferFrame]

func _WorldService_OpenTargetADB_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(WorldServiceServer).OpenTargetADB(&grpc.GenericServerStream[ADBFrame, ADBFrame]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorldService_OpenTargetADBServer = grpc.BidiStreamingServer[ADBFrame, ADBFrame]

func _WorldService_GetLiveSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLiveSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorldServiceServer).GetLiveSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorldService_GetLiveSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorldServiceServer).GetLiveSnapshot(ctx, req.(*GetLiveSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorldService_SubscribeObservations_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeObservationsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WorldServiceServer).SubscribeObservations(m, &grpc.GenericServerStream[SubscribeObservationsRequest, ObservationRecord]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorldService_SubscribeObservationsServer = grpc.ServerStreamingServer[ObservationRecord]

func _WorldService_SubscribeMetrics_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeMetricsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WorldServiceServer).SubscribeMetrics(m, &grpc.GenericServerStream[SubscribeMetricsRequest, MetricSample]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorldService_SubscribeMetricsServer = grpc.ServerStreamingServer[MetricSample]

func _WorldService_StartCapture_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartCaptureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorldServiceServer).StartCapture(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorldService_StartCapture_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorldServiceServer).StartCapture(ctx, req.(*StartCaptureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorldService_RequestCapture_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestCaptureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorldServiceServer).RequestCapture(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorldService_RequestCapture_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorldServiceServer).RequestCapture(ctx, req.(*RequestCaptureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorldService_StopCapture_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopCaptureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorldServiceServer).StopCapture(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorldService_StopCapture_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorldServiceServer).StopCapture(ctx, req.(*StopCaptureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorldService_GetObservationBundle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetObservationBundleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorldServiceServer).GetObservationBundle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorldService_GetObservationBundle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorldServiceServer).GetObservationBundle(ctx, req.(*GetObservationBundleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorldService_GetIncident_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIncidentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorldServiceServer).GetIncident(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorldService_GetIncident_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorldServiceServer).GetIncident(ctx, req.(*GetIncidentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorldService_DeclareExport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeclareExportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorldServiceServer).DeclareExport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorldService_DeclareExport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorldServiceServer).DeclareExport(ctx, req.(*DeclareExportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorldService_PreviewChangeSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PreviewChangeSetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorldServiceServer).PreviewChangeSet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorldService_PreviewChangeSet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorldServiceServer).PreviewChangeSet(ctx, req.(*PreviewChangeSetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorldService_CommitExport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitExportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorldServiceServer).CommitExport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorldService_CommitExport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorldServiceServer).CommitExport(ctx, req.(*CommitExportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorldService_TransitionAgentGeneration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransitionAgentGenerationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorldServiceServer).TransitionAgentGeneration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorldService_TransitionAgentGeneration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorldServiceServer).TransitionAgentGeneration(ctx, req.(*TransitionAgentGenerationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorldService_TransitionTargetGeneration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransitionTargetGenerationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorldServiceServer).TransitionTargetGeneration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorldService_TransitionTargetGeneration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorldServiceServer).TransitionTargetGeneration(ctx, req.(*TransitionTargetGenerationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorldService_TransitionTargetRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransitionTargetRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorldServiceServer).TransitionTargetRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorldService_TransitionTargetRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorldServiceServer).TransitionTargetRun(ctx, req.(*TransitionTargetRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorldService_CreateTargetOperation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTargetOperationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorldServiceServer).CreateTargetOperation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorldService_CreateTargetOperation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorldServiceServer).CreateTargetOperation(ctx, req.(*CreateTargetOperationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorldService_TransitionTargetOperation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransitionTargetOperationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorldServiceServer).TransitionTargetOperation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorldService_TransitionTargetOperation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorldServiceServer).TransitionTargetOperation(ctx, req.(*TransitionTargetOperationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorldService_CreateIncident_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateIncidentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorldServiceServer).CreateIncident(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorldService_CreateIncident_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorldServiceServer).CreateIncident(ctx, req.(*CreateIncidentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorldService_TransitionIncident_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransitionIncidentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorldServiceServer).TransitionIncident(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorldService_TransitionIncident_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorldServiceServer).TransitionIncident(ctx, req.(*TransitionIncidentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorldService_GetExec_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetExecRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorldServiceServer).GetExec(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorldService_GetExec_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorldServiceServer).GetExec(ctx, req.(*GetExecRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorldService_CreateExec_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateExecRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorldServiceServer).CreateExec(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorldService_CreateExec_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorldServiceServer).CreateExec(ctx, req.(*CreateExecRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorldService_TransitionExec_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransitionExecRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorldServiceServer).TransitionExec(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorldService_TransitionExec_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorldServiceServer).TransitionExec(ctx, req.(*TransitionExecRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorldService_FinalizeExec_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FinalizeExecRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorldServiceServer).FinalizeExec(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorldService_FinalizeExec_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorldServiceServer).FinalizeExec(ctx, req.(*FinalizeExecRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WorldService_ServiceDesc is the grpc.ServiceDesc for WorldService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WorldService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "world.v1.WorldService",
	HandlerType: (*WorldServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AcquireResearchSession",
			Handler:    _WorldService_AcquireResearchSession_Handler,
		},
		{
			MethodName: "GetResearchSession",
			Handler:    _WorldService_GetResearchSession_Handler,
		},
		{
			MethodName: "WaitResearchSession",
			Handler:    _WorldService_WaitResearchSession_Handler,
		},
		{
			MethodName: "RenewLease",
			Handler:    _WorldService_RenewLease_Handler,
		},
		{
			MethodName: "ReleaseResearchSession",
			Handler:    _WorldService_ReleaseResearchSession_Handler,
		},
		{
			MethodName: "CreateTarget",
			Handler:    _WorldService_CreateTarget_Handler,
		},
		{
			MethodName: "GetTarget",
			Handler:    _WorldService_GetTarget_Handler,
		},
		{
			MethodName: "StartTargetRun",
			Handler:    _WorldService_StartTargetRun_Handler,
		},
		{
			MethodName: "WaitTargetRun",
			Handler:    _WorldService_WaitTargetRun_Handler,
		},
		{
			MethodName: "StopTargetRun",
			Handler:    _WorldService_StopTargetRun_Handler,
		},
		{
			MethodName: "ResetTarget",
			Handler:    _WorldService_ResetTarget_Handler,
		},
		{
			MethodName: "DestroyTarget",
			Handler:    _WorldService_DestroyTarget_Handler,
		},
		{
			MethodName: "RequestRecovery",
			Handler:    _WorldService_RequestRecovery_Handler,
		},
		{
			MethodName: "QuarantineTarget",
			Handler:    _WorldService_QuarantineTarget_Handler,
		},
		{
			MethodName: "GetLiveSnapshot",
			Handler:    _WorldService_GetLiveSnapshot_Handler,
		},
		{
			MethodName: "StartCapture",
			Handler:    _WorldService_StartCapture_Handler,
		},
		{
			MethodName: "RequestCapture",
			Handler:    _WorldService_RequestCapture_Handler,
		},
		{
			MethodName: "StopCapture",
			Handler:    _WorldService_StopCapture_Handler,
		},
		{
			MethodName: "GetObservationBundle",
			Handler:    _WorldService_GetObservationBundle_Handler,
		},
		{
			MethodName: "GetIncident",
			Handler:    _WorldService_GetIncident_Handler,
		},
		{
			MethodName: "DeclareExport",
			Handler:    _WorldService_DeclareExport_Handler,
		},
		{
			MethodName: "PreviewChangeSet",
			Handler:    _WorldService_PreviewChangeSet_Handler,
		},
		{
			MethodName: "CommitExport",
			Handler:    _WorldService_CommitExport_Handler,
		},
		{
			MethodName: "TransitionAgentGeneration",
			Handler:    _WorldService_TransitionAgentGeneration_Handler,
		},
		{
			MethodName: "TransitionTargetGeneration",
			Handler:    _WorldService_TransitionTargetGeneration_Handler,
		},
		{
			MethodName: "TransitionTargetRun",
			Handler:    _WorldService_TransitionTargetRun_Handler,
		},
		{
			MethodName: "CreateTargetOperation",
			Handler:    _WorldService_CreateTargetOperation_Handler,
		},
		{
			MethodName: "TransitionTargetOperation",
			Handler:    _WorldService_TransitionTargetOperation_Handler,
		},
		{
			MethodName: "CreateIncident",
			Handler:    _WorldService_CreateIncident_Handler,
		},
		{
			MethodName: "TransitionIncident",
			Handler:    _WorldService_TransitionIncident_Handler,
		},
		{
			MethodName: "GetExec",
			Handler:    _WorldService_GetExec_Handler,
		},
		{
			MethodName: "CreateExec",
			Handler:    _WorldService_CreateExec_Handler,
		},
		{
			MethodName: "TransitionExec",
			Handler:    _WorldService_TransitionExec_Handler,
		},
		{
			MethodName: "FinalizeExec",
			Handler:    _WorldService_FinalizeExec_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "OpenExec",
			Handler:       _WorldService_OpenExec_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "OpenTargetExec",
			Handler:       _WorldService_OpenTargetExec_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "PushTargetFile",
			Handler:       _WorldService_PushTargetFile_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "PullTargetFile",
			Handler:       _WorldService_PullTargetFile_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "OpenTargetADB",
			Handler:       _WorldService_OpenTargetADB_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "SubscribeObservations",
			Handler:       _WorldService_SubscribeObservations_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SubscribeMetrics",
			Handler:       _WorldService_SubscribeMetrics_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "world/v1/world.proto",
}
